# GET test
GET http://localhost:8080/

# POST create a new manifest
POST http://localhost:8080/manifest
Content-Type: application/json
{
    "name": "demo-api",
    "version": "0.1.0",
    "description": "create manifest with easy-routes"
}

#GET name
GET http://localhost:8080/manifest/demo-api

#PATCH name
PATCH http://localhost:8080/manifest/demo-api
Content-Type: application/json
{
    "name": "demo-api",
    "spread": [
    {
        "name": "eastcoast",
        "weight": 80,
        "requirements": {
        "zone": "us-east-1"
        }
    },{
        "name": "westcoast",
        "weight": 20,
        "requirements": {
        "zone": "us-west-1"
        }
    }]
}
